### ISSUE TITLE
spurious error from cdecl regarding __stdcall pointers

### ISSUE THREAD

**Issue by blipvert** [paul-j-lucas/cdecl#13]
Given the query 
> `cdecl> declare foo as pointer to pointer to stdcall function (void) returning int`

cdecl correctly responds
> `int (__stdcall **foo)(void);`

However, when the output is given back to cdecl
> `cdecl> explain int (__stdcall **foo)(void)`

it erroneously complains
> `error: "__stdcall": can be used only for functions and pointers to function`

Note that the given expression is accepted without error by Microsoft's x86 compiler.

**Comment by paul-j-lucas** [comment]
I just pushed a fix. Do a `git pull`, try it out, and let me know.

**Comment by blipvert** [comment]
Thanks for the quick response!  Can confirm it now works as expected.  Closing the issue.
