### ISSUE TITLE
FreeBSD port: Configure Failiure

### ISSUE THREAD

**Issue by lrosenman** [paul-j-lucas/cdecl#15]
I got the following trying to update from 8.0->11.2:

configure:4483: cc -V >&5
cc: error: argument to '-V' is missing (expected 1 value)
cc: error: no input files
configure:4494: $? = 1
configure:4483: cc -qversion >&5
cc: error: unknown argument '-qversion'; did you mean '--version'?
cc: error: no input files
configure:4494: $? = 1
configure:4483: cc -version >&5
cc: error: unknown argument '-version'; did you mean '--version'?
cc: error: no input files
configure:4494: $? = 1
configure:4514: checking whether the C compiler works
configure:4536: cc -O2 -pipe  -fstack-protector-strong -fno-strict-aliasing  -I/usr/local/include  -L/usr/local/lib -fstack-protector-strong  conftest.c  >&5
conftest.c:7:21: warning: missing terminating '"' character [-Winvalid-pp-token]
#define PACKAGE_URL "https://github.com/paul-j-lucas/cdecl
                    ^
conftest.c:8:1: warning: missing terminating '"' character [-Winvalid-pp-token]
"
^
conftest.c:8:1: error: expected identifier or '('
2 warnings and 1 error generated.
configure:4540: $? = 1
configure:4578: result: no
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "cdecl"
| #define PACKAGE_TARNAME "cdecl"
| #define PACKAGE_VERSION "11.2"
| #define PACKAGE_STRING "cdecl 11.2"
| #define PACKAGE_BUGREPORT "https://github.com/paul-j-lucas/cdecl/issues"
| #define PACKAGE_URL "https://github.com/paul-j-lucas/cdecl
| "
| #define PACKAGE "cdecl"
| #define VERSION "11.2"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:4583: error: in `/home/ler/FreeBSD/ports/devel/cdecl/work/cdecl-cdecl-11.2':
configure:4586: error: C compiler cannot create executables
See `config.log' for more details

help?

**Comment by lrosenman** [comment]
this line is the problem:
PACKAGE_NAME " home page: " PACKAGE_URL "\n",

the COPT(ALT_TOKENS), 
after it is new.  8.0 still compiles just fine. 

I'm not sure what else to tell you.

This is on my home machine, that I recently upgraded to FreeBSD 14-CURRENT, clang 12.0.1

Can you look?

**Comment by paul-j-lucas** [comment]
The machine I've been using, `home.lerctr.org`, had been rarely ssh'able (including now), so I can't log in to test it.

**Comment by paul-j-lucas** [comment]
I think sometimes autotools is picky. In `configure.ac`, try changing:
```
AC_INIT(
  [cdecl],
  [11.2],
  [https://github.com/paul-j-lucas/cdecl/issues],
  [],
  [https://github.com/paul-j-lucas/cdecl]
)
```
to:
```
AC_INIT([cdecl],[11.2],[https://github.com/paul-j-lucas/cdecl/issues],[],[https://github.com/paul-j-lucas/cdecl])
```
i.e., make it all a single line with no whitespace.

**Comment by lrosenman** [comment]
> The machine I've been using, `home.lerctr.org`, had been rarely ssh'able (including now), so I can't log in to test it.

What error do you get?  It should be up/accessable

**Comment by paul-j-lucas** [comment]
It just times out on port 22.

That said, it just now (finally) worked.  But for the past few months, it's _not_ worked more than it's worked.

**Comment by paul-j-lucas** [comment]
FYI, I just tried my own 1-line fix and it works. I did:
```
git pull
git clean -xdf
./bootstrap
CC=clang ./configure --without-readline
make
```
I've deleted the old 11.2 release, force-moved the 11.2 tag, and re-uploaded a _new_ 11.2 release.

**Comment by lrosenman** [comment]
> It just times out on port 22.
> 
> That said, it just now (finally) worked. But for the past few months, it's _not_ worked more than it's worked.

Yeah, my firewall was being STOOPID(sic) on 2 rules.  I just deleted and recreated them and they seem to be sticking.

If that happens again, please send me mail (ler@FreeBSD.org)

**Comment by lrosenman** [comment]
That fixed it in the ports structure as well.  Thanks for the quick work!
