### ISSUE TITLE
Unable to declare an explanation with "ptr"

### ISSUE THREAD

**Issue by jengelh** [paul-j-lucas/cdecl#18]
The explain command's output is normally usable a command in its own right (and vice-versa), but this falls on its feet when the variable name is called ptr:
```
c++decl> explain void *ptr
declare ptr as pointer to void
c++decl> declare ptr as pointer to void
                 ^
18: syntax error: "ptr": name or operator expected
```

**Comment by paul-j-lucas** [comment]
That's because `ptr` is a cdecl keyword that's a shorthand for `pointer`.

**Comment by paul-j-lucas** [comment]
I could perhaps add code to check to see if a token is a cdecl keyword and include that in the error message.  Cdecl already does that for C/C++ keywords, e.g.:
```
cdecl> explain void *switch
24: syntax error: "switch": cast or declaration expected ("switch" is a keyword)
```
but not currently for cdecl keywords.

**Comment by paul-j-lucas** [comment]
As of [`306ff626412a`](https://github.com/paul-j-lucas/cdecl/commit/306ff626412a15519d90a393f1efd82c05b64b0d), cdecl token checks are done.
