### ISSUE TITLE
Website SSL certificate has expired

### ISSUE THREAD

**Issue by jwilo** [paul-j-lucas/cdecl#25]
Looks like the SSL certificate for cdecl.org expired 4 days ago, as Chrome is now throwing a NET::ERR_CERT_DATE_INVALID error.

**Comment by paul-j-lucas** [comment]
I have no affiliation with `cdecl.org`.  See [here](https://github.com/paul-j-lucas/cdecl/blob/master/README-blocks.txt).  Complain to the site's maintainer.
