### ISSUE TITLE
syntax error for user defined literal operator with trailing return type

### ISSUE THREAD

**Issue by IOBYTE** [paul-j-lucas/cdecl#3]
I'm getting an error for:
```
c++decl> explain auto operator "" _numch(const char *ch, std::size_t size) noexcept -> std::size_t;
                               ^
23: syntax error: """: cast or declaration expected
```

**Comment by paul-j-lucas** [comment]
User-defined literals are currently not supported. (The manual page omits this fact.) I may get around to adding support for it.

**Comment by paul-j-lucas** [comment]
FYI: I'm almost done with adding user-defined literal support. A separate issue with your example, however, is that `size_t` currently is only in the global namespace (for C) and _not_ also in the `std` namespace. I think it'll actually take more code to have the same name in both scopes.

**Comment by paul-j-lucas** [comment]
I just pushed a change for user-define literal support. Try it out (minding the `size_t` issue mentioned earlier).

**Comment by IOBYTE** [comment]
Thanks for the quick fix.  It's working for me now.  I had no clue what this code was doing when I saw it 3 days ago here: https://sourceforge.net/p/cppcheck/discussion/general/thread/703df00a29/
I use your program when I come across something like this that I don't understand and I was surprised it didn't work.  Thanks again for the quick turnaround.

**Comment by paul-j-lucas** [comment]
I've hacked in support for `std::size_t`.

**Comment by IOBYTE** [comment]
Cool. Everything works now. Thanks again.
