### ISSUE TITLE
flex 2.5.27

### ISSUE THREAD

**Issue by polluks** [paul-j-lucas/cdecl#31]
...part of my SDK
```
Making all in src
make[1]: Entering directory '/RAM/cdecl-master/src'
/bin/sh ../ylwrap parser.y y.tab.c parser.c y.tab.h `echo parser.c | sed -e s/cc$/hh/ -e s/cpp$/hpp/ -e s/cxx$/hxx/ -e s/c++$/h++/ -e s/c$/h/` y.output parser.output -- bison -o y.tab.c -d
updating parser.h
/bin/sh ../ylwrap lexer.l lex.yy.c lexer.c -- flex
/RAM/cdecl-master/src/lexer.l:32: unrecognized '%' directive
/RAM/cdecl-master/src/lexer.l:33: bad character: #
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: bad character: "
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: bad character: .
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: bad character: "
/RAM/cdecl-master/src/lexer.l:33: bad character: /
/RAM/cdecl-master/src/lexer.l:33: bad character: *
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: unknown error processing section 1
/RAM/cdecl-master/src/lexer.l:33: bad character: *
/RAM/cdecl-master/src/lexer.l:33: bad character: /
/RAM/cdecl-master/src/lexer.l:34: bad character: }
make[1]: *** [Makefile:1853: lexer.c] Error 1
make[1]: Leaving directory '/RAM/cdecl-master/src'
make: *** [Makefile:1459: all-recursive] Error 1

**Comment by paul-j-lucas** [comment]
The flex `%top` directive was added in version 2.5.30 that was released in 2003. I'm kind of not leaning towards supporting 20-year-old software. Upgrade your flex version.

**Comment by polluks** [comment]
I see.

**Comment by paul-j-lucas** [comment]
It turns out that the M4 macros `AX_PROG_FLEX_VERSION` and `AX_PROG_BISON_VERSION` exist, so now **cdecl** requires flex 2.5.30 or later and bison 3.4.2 or later.

**Comment by paul-j-lucas** [comment]
BTW, unless you plan on modifying **cdecl**, you don't need either flex or bison if you download a released version.

**Comment by polluks** [comment]
I want to do a MorphOS port, but flex 2.5.30 requires fork() which is not implemented. We are stuck to version 2.5.27 :-(
https://en.wikipedia.org/wiki/Let_them_eat_cake

**Comment by paul-j-lucas** [comment]
As I said, I don't see why I should have to support a flex version released in 2003.

Flex uses `fork()` apparently only for debugging purposes which means you could probably just disable all of it.  From `ChangeLog`:

```
2003-03-12  John Millaway <john43@users.sourceforge.net>

        * buf.c, filter.c, flex.skl, flexdef.h, main.c, misc.c, options.c,
        options.h, scan.l, tests/test-reject/scanner.l: More m4 macro
        conversions.  Added debugging option --preproc-level=NUM.
```

If I were you, I'd start with flex 2.5.30 source and patch it to assume that `preproc_level` is `0` which is what you get via the undocumented `--preproc=0` option. When `0`, flex won't call `filter_apply_chain()` which is the function that calls `fork()`.  Just `#ifdef 0` ... `#endif` out all that code and build flex that way and see what happens.
