### ISSUE TITLE
Invalid function declarator accepted as valid

### ISSUE THREAD

**Issue by mzoz** [paul-j-lucas/cdecl#32]
For example `int foo()()()` is comprehended as "declare foo as function returning function returning function returning int", but it's an invalid declarator and won't pass compilation, please help thanks!

**Comment by paul-j-lucas** [comment]
When I do it, I get:
```
declare foo as function returning integer
```
(which is also wrong).

**Comment by mzoz** [comment]
No worries Paul, it's indeed syntactically correct, but violates some misc constrain, I've just found this footnote on c standard:
"A function declarator shall not specify a return type that is a function type or an array
type." on page 118
https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1256.pdf

**Comment by paul-j-lucas** [comment]
Why did you close it? It's still wrong.

**Comment by paul-j-lucas** [comment]
I tried a few obvious things, but none worked (without breaking other tests). It might take a while.

**Comment by paul-j-lucas** [comment]
The fix is kind of hack-ish.  The code between adding functions and adding arrays is similar. I suspect that there's a more elegant fix waiting to be discovered that also unifies the code between arrays and functions.
